import createModuleRoutes from "../PageConfig/createConf";

const schoolInfoCreateFields = [
  { type: "text", name: "Experience" },
  { type: "number", name: "Students" },
  { type: "number", name: "Teachers" },
  { type: "text", name: "Awards" },
  { type: "text", name: "School_Name" },
  { type: "text", name: "Short_Name" },
  { type: "file", name: "Logo_Url", multiple: false },
  { type: "file", name: "Favicon_Url", multiple: false },
  { type: "text", name: "Motto" },
  { type: "date", name: "Established_Year" },
  { type: "text", name: "Address" },
  { type: "text", name: "City" },
  { type: "text", name: "State" },
  { type: "text", name: "Pin_Code" },
  { type: "text", name: "Alternate_Phone" },
  { type: "text", name: "Email" },
  { type: "text", name: "Website" },
  { type: "date", name: "Academic_Year_Start" },
  { type: "date", name: "Academic_Year_End" },
  { type: "text", name: "Youtube_Url" },
  { type: "text", name: "Linkedin_Url" },
  { type: "text", name: "Instagram_Url" },
  { type: "text", name: "Twitter_Url" },
  { type: "text", name: "Board_Affiliation" },
  { type: "text", name: "Board_Affiliation_Number" },
  { type: "text", name: "Latitude" },
  { type: "text", name: "Longitude" },
  { type: "text", name: "Contact_Person_Name" },
  { type: "text", name: "Contact_Person_Position" },
  { type: "text", name: "Contact_Person_Phone" },
  { type: "text", name: "Medium_Of_Instruction" },
  { type: "number", name: "Display_Order" },
  { type: "select", name: "Is_Active", options: ["active", "inactive"] },
];

const schoolInfoUpdateFields = [
  { type: "text", name: "Experience" },
  { type: "number", name: "Students" },
  { type: "number", name: "Teachers" },
  { type: "text", name: "Awards" },
  { type: "text", name: "School_Name" },
  { type: "text", name: "Short_Name" },
  { type: "file", name: "Logo_Url", multiple: false },
  { type: "file", name: "Favicon_Url", multiple: false },
  { type: "text", name: "Motto" },
  { type: "date", name: "Established_Year" },
  { type: "text", name: "Address" },
  { type: "text", name: "City" },
  { type: "text", name: "State" },
  { type: "text", name: "Pin_Code" },
  { type: "text", name: "Alternate_Phone" },
  { type: "text", name: "Email" },
  { type: "text", name: "Website" },
  { type: "date", name: "Academic_Year_Start" },
  { type: "date", name: "Academic_Year_End" },
  { type: "text", name: "Youtube_Url" },
  { type: "text", name: "Linkedin_Url" },
  { type: "text", name: "Instagram_Url" },
  { type: "text", name: "Twitter_Url" },
  { type: "text", name: "Board_Affiliation" },
  { type: "text", name: "Board_Affiliation_Number" },
  { type: "text", name: "Latitude" },
  { type: "text", name: "Longitude" },
  { type: "text", name: "Contact_Person_Name" },
  { type: "text", name: "Contact_Person_Position" },
  { type: "text", name: "Contact_Person_Phone" },
  { type: "text", name: "Medium_Of_Instruction" },
  { type: "number", name: "Display_Order" },
  { type: "select", name: "Is_Active", options: ["active", "inactive"] },
];

const SchoolInfo = createModuleRoutes('school-info', schoolInfoCreateFields, schoolInfoUpdateFields);
export default SchoolInfo;
