const express = require("express");
const { adminAuth } = require("../../middleware/authMiddleware");
const achievementsRoutes = require("../routes/achievementsRoutes");
const adminsRoutes = require("../routes/adminsRoutes");
const admissionRoutes = require("../routes/admissionRoutes");
const admission_open_messageRoutes = require("../routes/admission_open_messageRoutes");
const blogRoutes = require("../routes/blogRoutes");
const facilityRoutes = require("../routes/facilityRoutes");
const gallery_categoryRoutes = require("../routes/gallery_categoryRoutes");
const galleryRoutes = require("../routes/galleryRoutes");

const messagesRoutes = require("../routes/messagesRoutes");
const notificationRoutes = require("../routes/notificationRoutes");
const pages_categoryRoutes = require("../routes/pages_categoryRoutes");
const pagesRoutes = require("../routes/pagesRoutes");
const posterRoutes = require("../routes/posterRoutes");
const quick_linkRoutes = require("../routes/quick_linkRoutes");
const school_infoRoutes = require("../routes/school_infoRoutes");
const school_welcome_messageRoutes = require("../routes/school_welcome_messageRoutes");
const toper_categoryRoutes = require("../routes/toper_categoryRoutes");
const toperRoutes = require("../routes/toperRoutes");
const useful_linkRoutes = require("../routes/useful_linkRoutes");
const authRoutes = require("../routes/authRoutes");
const dash_boardRoutes = require("../routes/dash_boardRoutes");
const router = express.Router();

router.use("/achievements", adminAuth, achievementsRoutes);
router.use("/admins", adminAuth, adminsRoutes);
router.use("/admission", adminAuth, admissionRoutes);
router.use("/admission-open-message", adminAuth, admission_open_messageRoutes);
router.use("/blog", adminAuth, blogRoutes);
router.use("/facility", adminAuth, facilityRoutes);
router.use("/gallery-category", adminAuth, gallery_categoryRoutes);
router.use("/gallery", adminAuth, galleryRoutes);

router.use("/messages", adminAuth, messagesRoutes);
router.use("/notification", adminAuth, notificationRoutes);
router.use("/pages-category", adminAuth, pages_categoryRoutes);
router.use("/pages", adminAuth, pagesRoutes);
router.use("/poster", adminAuth, posterRoutes);
router.use("/quick-link", adminAuth, quick_linkRoutes);
router.use("/school-info", adminAuth, school_infoRoutes);
router.use("/school-welcome-message", adminAuth, school_welcome_messageRoutes);
router.use("/toper-category", adminAuth, toper_categoryRoutes);
router.use("/toper", adminAuth, toperRoutes);
router.use("/useful-link", adminAuth, useful_linkRoutes);
router.use('/auth', authRoutes);
router.use("/", adminAuth, dash_boardRoutes);
module.exports = router;
